matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        - npm
      before_install:
        - cd ./Front-end
      script:
        - npm run build

    - language: node_js
      node_js:
        - "stable"
      cache:
        - npm
      before_install:
        - cd ./Back-end
      script:
        - npm run build
      after_success:
        - cd ..
        - git subtree push --prefix Back-end origin server
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: LDgXzMqdlEMSrv4ySm9+nltH2ksJI0ZnYkeC6t/Le9Q14fc43HW8tMH0x9Ex/ay6mTvy85ouG46dW9I/c4FjrYTL6/eEQF038zES1eZJOO6bfR80pXwhZ+kMlEFF4G9/owMHsukDZ2Fwyfjicj1T4+lftwC5qTL3Eso0t7GwOS6wApJNJseoKgvrXvAxYnMDjdqBEw3CqUWHWO21uTjmBK98h8AoYwqMGhe2i6dpBLlaKnKuxde4XOhmMi3jfXeD83pNCsWI1SQhYwOBoq1d5pjH1nUHhVTbf95OioGhNEGlbcHs34+nSecVttqe2tn65PLHrEIxZDcOeJecwxUyPaeyreY1ApDgWpd+poJWVmaxYWqnYSS/aLcT0ksZhuEioErJpz1RE2RA41JFyowE6NG6/fQZiMhw9dUxJP37FRwXTNGEZM6FehWjK5r61mx3I64H0upBCs2hGvDQiH4CFb/8xxv84Dh54H+imTq8C8eEOlDctTt1U/ruuNjk4Ij9nZFb5iPOGsT5IYHNvnlncViHpHd8GqX9q9yOtxkb2N5SIY/3hqLR1TTYvOIogyOPKyndCHH1XeDJDcRooYVe2xh9vGwncFjrS3uO+VBMFNCM4aSSBhQEAozQzDe7FXDea0E9FdP2mUAl7164+WooQe2xPZz6tWokSILriJJuCa0=
        app: cscc01backend
        on: server

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
