matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        - npm
      before_install:
        - cd ./Front-end
      script:
        - npm run build
    - language: node_js
      node_js:
        - "stable"
      cache:
        - npm
      before_install:
        - cd ./Back-end
      after_success:
        - rm -Rf ./src/test
        - npm run build
        - cd ..
        - git subtree push --prefix Back-end origin server

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
